deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

script:
  - rm .travis.yml README.md && find jars | tr '/' '\t' | cut -f2-4 | awk '{gsub(/\.pom$/, "");gsub(/\.jar$/, "");if (NF == 3) print}' | sort -u >index
